# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Cvs
version:      0.07
version_from: lib/Cvs.pm
installdirs:  site
requires:
    Class::Accessor:               0.17
    Cwd:                           2.04
    File::Temp:                    0.12
    FileHandle:                    2.0
    IO::Pty:                       1.02
    IPC::Run:                      0.74

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
